export interface AnimationProject {
  id: string;
  slug: string;
  title: string;
  category: string;
  categorySlug: string;
  categoryIcon: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  views: number;
  stars: number;
  likes: number;
  creator: string;
  creatorAvatar: string;
  creatorColor: string;
  gradientFrom: string;
  gradientTo: string;
  animationType: string;
  tags: string[];
  description: string;
  isNew?: boolean;
  isTrending?: boolean;
  isFeatured?: boolean;
  /* Netflix row classification — one or more rows this item belongs to */
  rows?: string[];
  /* Optional embedded video */
  video?: {
    platform: "youtube" | "tiktok" | "instagram" | "vimeo";
    url: string;           // embed-ready URL
    thumbnail?: string;
    label: string;         // e.g. "Watch on YouTube"
  };
  /* Rutas a archivos externos de cada animación */
  htmlPath?: string;
  cssPath?: string;
  jsPath?: string;
}

export const animations: AnimationProject[] = [
  {
    id: "1", slug: "neon-orbit-system",
    title: "Neon Orbit System",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Intermediate",
    views: 48200, stars: 312, likes: 891,
    creator: "axeldev", creatorAvatar: "A", creatorColor: "#8b5cf6",
    gradientFrom: "#8b5cf6", gradientTo: "#ec4899",
    animationType: "orbit",
    tags: ["css", "neon", "orbit", "glow"],
    description: "A mesmerizing multi-ring orbital system built with pure CSS. Each ring rotates at a different speed creating a hypnotic planetary motion effect.",
    isTrending: true, isFeatured: true,
    rows: ["trending", "css"],
    htmlPath: "/animations/neon-orbit-system/index.html",
    cssPath: "/animations/neon-orbit-system/styles.css",
    jsPath: "/animations/neon-orbit-system/main.js",
  },
  {
    id: "2", slug: "liquid-wave-equalizer",
    title: "Liquid Wave Equalizer",
    category: "JavaScript", categorySlug: "javascript", categoryIcon: "⚡",
    difficulty: "Beginner",
    views: 62400, stars: 445, likes: 1204,
    creator: "motioncraft", creatorAvatar: "M", creatorColor: "#06b6d4",
    gradientFrom: "#06b6d4", gradientTo: "#3b82f6",
    animationType: "wave",
    tags: ["wave", "audio", "bars", "reactive"],
    description: "Fluid wave animation bars that respond to rhythm. Perfect for music players, loaders, or ambient UI elements.",
    isTrending: true,
    rows: ["trending", "javascript"],
    htmlPath: "/animations/liquid-wave-equalizer/index.html",
    cssPath: "/animations/liquid-wave-equalizer/styles.css",
    jsPath: "/animations/liquid-wave-equalizer/main.js",
  },
  {
    id: "3", slug: "particle-galaxy-field",
    title: "Particle Galaxy Field",
    category: "Canvas", categorySlug: "canvas", categoryIcon: "🌌",
    difficulty: "Advanced",
    views: 91300, stars: 723, likes: 2108,
    creator: "stardustfx", creatorAvatar: "S", creatorColor: "#ec4899",
    gradientFrom: "#a855f7", gradientTo: "#3b82f6",
    animationType: "particles",
    tags: ["canvas", "particles", "galaxy", "interactive"],
    description: "500+ interconnected particles with physics simulation, gravity, mouse interaction and RGB cycling.",
    isTrending: true, isFeatured: true,
    rows: ["trending", "particles", "canvas"],
    htmlPath: "/animations/particle-galaxy-field/index.html",
    cssPath: "/animations/particle-galaxy-field/styles.css",
    jsPath: "/animations/particle-galaxy-field/main.js",
  },
  {
    id: "4", slug: "aurora-gradient-flow",
    title: "Aurora Gradient Flow",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Beginner",
    views: 35700, stars: 267, likes: 743,
    creator: "chromawave", creatorAvatar: "C", creatorColor: "#10b981",
    gradientFrom: "#ec4899", gradientTo: "#8b5cf6",
    animationType: "aurora",
    tags: ["css", "gradient", "aurora", "background"],
    description: "Sweeping aurora borealis effect with smooth color transitions. Stunning as a hero background.",
    isNew: true,
    rows: ["new", "css"],
    htmlPath: "/animations/aurora-gradient-flow/index.html",
    cssPath: "/animations/aurora-gradient-flow/styles.css",
    jsPath: "/animations/aurora-gradient-flow/main.js",
  },
  {
    id: "5", slug: "matrix-code-rain",
    title: "Matrix Code Rain",
    category: "Canvas", categorySlug: "canvas", categoryIcon: "🌌",
    difficulty: "Intermediate",
    views: 77400, stars: 589, likes: 1876,
    creator: "stardustfx", creatorAvatar: "S", creatorColor: "#ec4899",
    gradientFrom: "#10b981", gradientTo: "#06b6d4",
    animationType: "matrix",
    tags: ["canvas", "matrix", "rain", "code"],
    description: "The iconic Matrix digital rain effect with canvas. Customizable character sets, speed and color themes.",
    isTrending: true,
    rows: ["trending", "canvas"],
    htmlPath: "/animations/matrix-code-rain/index.html",
    cssPath: "/animations/matrix-code-rain/styles.css",
    jsPath: "/animations/matrix-code-rain/main.js",
  },
  {
    id: "6", slug: "morphing-blob-shape",
    title: "Morphing Blob Shape",
    category: "SVG", categorySlug: "svg", categoryIcon: "🎨",
    difficulty: "Intermediate",
    views: 29800, stars: 198, likes: 621,
    creator: "uicraft", creatorAvatar: "U", creatorColor: "#f59e0b",
    gradientFrom: "#f59e0b", gradientTo: "#ef4444",
    animationType: "morph",
    tags: ["svg", "morph", "blob", "shape"],
    description: "Smoothly morphing SVG blob with configurable randomness. Great for abstract backgrounds and hero sections.",
    isNew: true,
    rows: ["new"],
    htmlPath: "/animations/morphing-blob-shape/index.html",
    cssPath: "/animations/morphing-blob-shape/styles.css",
    jsPath: "/animations/morphing-blob-shape/main.js",
  },
  {
    id: "7", slug: "glitch-text-effect",
    title: "Glitch Text Effect",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Intermediate",
    views: 54300, stars: 401, likes: 1342,
    creator: "axeldev", creatorAvatar: "A", creatorColor: "#8b5cf6",
    gradientFrom: "#3b82f6", gradientTo: "#ec4899",
    animationType: "glitch",
    tags: ["css", "glitch", "text", "cyberpunk"],
    description: "A cyberpunk-style glitch text animation with chromatic aberration and scan-line effects.",
    isTrending: true,
    rows: ["trending", "css"],
    htmlPath: "/animations/glitch-text-effect/index.html",
    cssPath: "/animations/glitch-text-effect/styles.css",
    jsPath: "/animations/glitch-text-effect/main.js",
  },
  {
    id: "8", slug: "3d-floating-cards",
    title: "3D Floating Cards",
    category: "JavaScript", categorySlug: "javascript", categoryIcon: "⚡",
    difficulty: "Advanced",
    views: 41600, stars: 334, likes: 987,
    creator: "motioncraft", creatorAvatar: "M", creatorColor: "#06b6d4",
    gradientFrom: "#7c3aed", gradientTo: "#06b6d4",
    animationType: "cards3d",
    tags: ["js", "3d", "parallax", "mouse"],
    description: "Mouse-reactive 3D perspective card tilt with floating depth layers. Premium UI microinteraction.",
    isNew: true, isFeatured: true,
    rows: ["new", "javascript"],
    htmlPath: "/animations/3d-floating-cards/index.html",
    cssPath: "/animations/3d-floating-cards/styles.css",
    jsPath: "/animations/3d-floating-cards/main.js",
  },
  {
    id: "9", slug: "neon-pulse-loader",
    title: "Neon Pulse Loader",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Beginner",
    views: 38100, stars: 276, likes: 812,
    creator: "chromawave", creatorAvatar: "C", creatorColor: "#10b981",
    gradientFrom: "#8b5cf6", gradientTo: "#3b82f6",
    animationType: "loader",
    tags: ["loader", "pulse", "neon", "css"],
    description: "A collection of neon-glowing pulse loaders. Ideal for dark-mode apps and developer tools.",
    rows: ["loading", "css"],
    htmlPath: "/animations/neon-pulse-loader/index.html",
    cssPath: "/animations/neon-pulse-loader/styles.css",
    jsPath: "/animations/neon-pulse-loader/main.js",
  },
  {
    id: "10", slug: "typewriter-terminal",
    title: "Typewriter Terminal",
    category: "JavaScript", categorySlug: "javascript", categoryIcon: "⚡",
    difficulty: "Beginner",
    views: 28900, stars: 198, likes: 543,
    creator: "codepoet", creatorAvatar: "P", creatorColor: "#34d399",
    gradientFrom: "#10b981", gradientTo: "#3b82f6",
    animationType: "typewriter",
    tags: ["typewriter", "terminal", "text", "typing"],
    description: "Multi-string typewriter with cursor, configurable speed and loop. Classic developer aesthetic.",
    rows: ["javascript"],
    htmlPath: "/animations/typewriter-terminal/index.html",
    cssPath: "/animations/typewriter-terminal/styles.css",
    jsPath: "/animations/typewriter-terminal/main.js",
  },
  {
    id: "11", slug: "fluid-ripple-click",
    title: "Fluid Ripple Click",
    category: "JavaScript", categorySlug: "javascript", categoryIcon: "⚡",
    difficulty: "Intermediate",
    views: 33500, stars: 245, likes: 734,
    creator: "uicraft", creatorAvatar: "U", creatorColor: "#f59e0b",
    gradientFrom: "#06b6d4", gradientTo: "#10b981",
    animationType: "ripple",
    tags: ["ripple", "click", "water", "fluid"],
    description: "Realistic water ripple effect on mouse click. Smooth canvas-based fluid simulation.",
    isNew: true,
    rows: ["new", "javascript", "canvas"],
    htmlPath: "/animations/fluid-ripple-click/index.html",
    cssPath: "/animations/fluid-ripple-click/styles.css",
    jsPath: "/animations/fluid-ripple-click/main.js",
  },
  {
    id: "12", slug: "css-grid-mosaic",
    title: "CSS Grid Mosaic",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Beginner",
    views: 21400, stars: 156, likes: 421,
    creator: "chromawave", creatorAvatar: "C", creatorColor: "#10b981",
    gradientFrom: "#ec4899", gradientTo: "#f59e0b",
    animationType: "mosaic",
    tags: ["css", "grid", "mosaic", "color"],
    description: "Animated color mosaic grid with staggered entrance and hover glow. Eye-catching gallery layout.",
    rows: ["css"],
    htmlPath: "/animations/css-grid-mosaic/index.html",
    cssPath: "/animations/css-grid-mosaic/styles.css",
    jsPath: "/animations/css-grid-mosaic/main.js",
  },
  // Cursor effects
  {
    id: "13", slug: "ghost-cursor",
    title: "Ghost Cursor Trail",
    category: "Cursors", categorySlug: "cursors", categoryIcon: "🖱",
    difficulty: "Beginner",
    views: 44300, stars: 312, likes: 920,
    creator: "axeldev", creatorAvatar: "A", creatorColor: "#8b5cf6",
    gradientFrom: "#8b5cf6", gradientTo: "#3b82f6",
    animationType: "loader",
    tags: ["cursor", "trail", "ghost", "mouse"],
    description: "Glowing ghost dots that follow the cursor with a smooth trailing effect.",
    isTrending: true,
    rows: ["trending", "cursors"],
    htmlPath: "/animations/ghost-cursor/index.html",
    cssPath: "/animations/ghost-cursor/styles.css",
    jsPath: "/animations/ghost-cursor/main.js",
  },
  {
    id: "14", slug: "magnetic-cursor",
    title: "Magnetic Cursor",
    category: "Cursors", categorySlug: "cursors", categoryIcon: "🖱",
    difficulty: "Intermediate",
    views: 31200, stars: 224, likes: 673,
    creator: "motioncraft", creatorAvatar: "M", creatorColor: "#06b6d4",
    gradientFrom: "#06b6d4", gradientTo: "#8b5cf6",
    animationType: "particles",
    tags: ["cursor", "magnetic", "button", "interaction"],
    description: "Buttons that magnetically attract the cursor on hover. Premium interaction feel.",
    isNew: true,
    rows: ["new", "cursors"],
    htmlPath: "/animations/magnetic-cursor/index.html",
    cssPath: "/animations/magnetic-cursor/styles.css",
    jsPath: "/animations/magnetic-cursor/main.js",
  },
  {
    id: "15", slug: "spotlight-cursor",
    title: "Spotlight Cursor",
    category: "Cursors", categorySlug: "cursors", categoryIcon: "🖱",
    difficulty: "Beginner",
    views: 27800, stars: 198, likes: 543,
    creator: "chromawave", creatorAvatar: "C", creatorColor: "#10b981",
    gradientFrom: "#f59e0b", gradientTo: "#ec4899",
    animationType: "aurora",
    tags: ["cursor", "spotlight", "dark", "light"],
    description: "A spotlight that follows the cursor revealing content in a dark canvas.",
    rows: ["cursors"],
    htmlPath: "/animations/spotlight-cursor/index.html",
    cssPath: "/animations/spotlight-cursor/styles.css",
    jsPath: "/animations/spotlight-cursor/main.js",
  },
  // Loading animations
  {
    id: "16", slug: "dna-helix-loader",
    title: "DNA Helix Loader",
    category: "Loading", categorySlug: "loading", categoryIcon: "⏳",
    difficulty: "Intermediate",
    views: 39100, stars: 287, likes: 801,
    creator: "stardustfx", creatorAvatar: "S", creatorColor: "#ec4899",
    gradientFrom: "#ec4899", gradientTo: "#8b5cf6",
    animationType: "orbit",
    tags: ["loader", "dna", "helix", "css"],
    description: "A double-helix spinner built entirely in CSS. Mesmerizing loading state.",
    isTrending: true,
    rows: ["trending", "loading", "css"],
    htmlPath: "/animations/dna-helix-loader/index.html",
    cssPath: "/animations/dna-helix-loader/styles.css",
    jsPath: "/animations/dna-helix-loader/main.js",
  },
  {
    id: "17", slug: "skeleton-shimmer",
    title: "Skeleton Shimmer",
    category: "Loading", categorySlug: "loading", categoryIcon: "⏳",
    difficulty: "Beginner",
    views: 52700, stars: 398, likes: 1120,
    creator: "uicraft", creatorAvatar: "U", creatorColor: "#f59e0b",
    gradientFrom: "#3b82f6", gradientTo: "#8b5cf6",
    animationType: "mosaic",
    tags: ["skeleton", "shimmer", "placeholder", "loading"],
    description: "Modern content placeholder skeleton with shimmer animation. Ready for any card layout.",
    isNew: true,
    rows: ["new", "loading"],
    htmlPath: "/animations/skeleton-shimmer/index.html",
    cssPath: "/animations/skeleton-shimmer/styles.css",
    jsPath: "/animations/skeleton-shimmer/main.js",
  },
  {
    id: "18", slug: "progress-neon-bar",
    title: "Neon Progress Bar",
    category: "Loading", categorySlug: "loading", categoryIcon: "⏳",
    difficulty: "Beginner",
    views: 19300, stars: 143, likes: 389,
    creator: "chromawave", creatorAvatar: "C", creatorColor: "#10b981",
    gradientFrom: "#10b981", gradientTo: "#06b6d4",
    animationType: "wave",
    tags: ["progress", "bar", "neon", "css"],
    description: "Animated neon progress bar with glow trail. Perfect for file upload or page load indicators.",
    rows: ["loading", "css"],
    htmlPath: "/animations/progress-neon-bar/index.html",
    cssPath: "/animations/progress-neon-bar/styles.css",
    jsPath: "/animations/progress-neon-bar/main.js",
  },
  // Hearts
  {
    id: "19", slug: "neon-heart-pulse",
    title: "Neon Heart Pulse",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Beginner",
    views: 73400, stars: 521, likes: 1893,
    creator: "motioncraft", creatorAvatar: "M", creatorColor: "#06b6d4",
    gradientFrom: "#ec4899", gradientTo: "#f43f5e",
    animationType: "ripple",
    tags: ["heart", "pulse", "neon", "love"],
    description: "Glowing neon heart that pulses and radiates rings. A viral Valentine's Day animation.",
    isTrending: true,
    rows: ["trending", "hearts", "css"],
    htmlPath: "/animations/neon-heart-pulse/index.html",
    cssPath: "/animations/neon-heart-pulse/styles.css",
    jsPath: "/animations/neon-heart-pulse/main.js",
  },
  {
    id: "20", slug: "heart-particle-burst",
    title: "Heart Particle Burst",
    category: "Canvas", categorySlug: "canvas", categoryIcon: "🌌",
    difficulty: "Advanced",
    views: 68900, stars: 492, likes: 1674,
    creator: "stardustfx", creatorAvatar: "S", creatorColor: "#ec4899",
    gradientFrom: "#f43f5e", gradientTo: "#ec4899",
    animationType: "particles",
    tags: ["heart", "particle", "burst", "canvas"],
    description: "Heart-shaped particle explosion on click with physics, gravity and color trails.",
    isTrending: true,
    rows: ["trending", "hearts", "particles", "canvas"],
    htmlPath: "/animations/heart-particle-burst/index.html",
    cssPath: "/animations/heart-particle-burst/styles.css",
    jsPath: "/animations/heart-particle-burst/main.js",
  },
  {
    id: "21", slug: "floating-hearts",
    title: "Floating Hearts",
    category: "CSS", categorySlug: "css", categoryIcon: "✨",
    difficulty: "Beginner",
    views: 41200, stars: 298, likes: 943,
    creator: "codepoet", creatorAvatar: "P", creatorColor: "#34d399",
    gradientFrom: "#ec4899", gradientTo: "#a855f7",
    animationType: "morph",
    tags: ["heart", "float", "love", "css"],
    description: "Hearts floating upward with random size and opacity. Dreamy romantic background.",
    rows: ["hearts", "css"],
    htmlPath: "/animations/floating-hearts/index.html",
    cssPath: "/animations/floating-hearts/styles.css",
    jsPath: "/animations/floating-hearts/main.js",
  },
  // Three.js
  {
    id: "22", slug: "particle-sphere-threejs",
    title: "Particle Sphere",
    category: "Three.js", categorySlug: "threejs", categoryIcon: "🧊",
    difficulty: "Advanced",
    views: 88200, stars: 641, likes: 1987,
    creator: "stardustfx", creatorAvatar: "S", creatorColor: "#ec4899",
    gradientFrom: "#8b5cf6", gradientTo: "#06b6d4",
    animationType: "orbit",
    tags: ["threejs", "sphere", "3d", "particles"],
    description: "Thousands of particles arranged in a rotating 3D sphere with wave distortion.",
    isTrending: true, isFeatured: true,
    rows: ["trending", "threejs", "particles"],
    htmlPath: "/animations/particle-sphere-threejs/index.html",
    cssPath: "/animations/particle-sphere-threejs/styles.css",
    jsPath: "/animations/particle-sphere-threejs/main.js",
  },
  {
    id: "23", slug: "galaxy-spiral-threejs",
    title: "Galaxy Spiral",
    category: "Three.js", categorySlug: "threejs", categoryIcon: "🧊",
    difficulty: "Advanced",
    views: 62400, stars: 487, likes: 1456,
    creator: "axeldev", creatorAvatar: "A", creatorColor: "#8b5cf6",
    gradientFrom: "#3b82f6", gradientTo: "#a855f7",
    animationType: "matrix",
    tags: ["threejs", "galaxy", "spiral", "stars"],
    description: "Procedurally generated galaxy spiral with 50,000 stars and bloom post-processing.",
    isTrending: true,
    rows: ["trending", "threejs"],
    htmlPath: "/animations/galaxy-spiral-threejs/index.html",
    cssPath: "/animations/galaxy-spiral-threejs/styles.css",
    jsPath: "/animations/galaxy-spiral-threejs/main.js",
  },
  {
    id: "24", slug: "liquid-blob-threejs",
    title: "Liquid Blob 3D",
    category: "Three.js", categorySlug: "threejs", categoryIcon: "🧊",
    difficulty: "Advanced",
    views: 44800, stars: 345, likes: 1012,
    creator: "motioncraft", creatorAvatar: "M", creatorColor: "#06b6d4",
    gradientFrom: "#06b6d4", gradientTo: "#10b981",
    animationType: "morph",
    tags: ["threejs", "blob", "liquid", "shader"],
    description: "Morphing liquid blob with custom GLSL shader and mouse-reactive distortion.",
    isNew: true,
    rows: ["new", "threejs"],
    htmlPath: "/animations/liquid-blob-threejs/index.html",
    cssPath: "/animations/liquid-blob-threejs/styles.css",
    jsPath: "/animations/liquid-blob-threejs/main.js",
  },
  // More particles
  {
    id: "25", slug: "fireflies",
    title: "Firefly Forest",
    category: "Canvas", categorySlug: "canvas", categoryIcon: "🌌",
    difficulty: "Beginner",
    views: 56300, stars: 412, likes: 1234,
    creator: "codepoet", creatorAvatar: "P", creatorColor: "#34d399",
    gradientFrom: "#10b981", gradientTo: "#f59e0b",
    animationType: "particles",
    tags: ["firefly", "particles", "canvas", "ambient"],
    description: "Glowing fireflies drifting with randomized paths and organic motion.",
    rows: ["particles", "canvas"],
    htmlPath: "/animations/fireflies/index.html",
    cssPath: "/animations/fireflies/styles.css",
    jsPath: "/animations/fireflies/main.js",
  },
  {
    id: "26", slug: "snow-particles",
    title: "Snow Particles",
    category: "Canvas", categorySlug: "canvas", categoryIcon: "🌌",
    difficulty: "Beginner",
    views: 48900, stars: 356, likes: 987,
    creator: "chromawave", creatorAvatar: "C", creatorColor: "#10b981",
    gradientFrom: "#3b82f6", gradientTo: "#06b6d4",
    animationType: "particles",
    tags: ["snow", "particles", "winter", "canvas"],
    description: "Falling snowflakes with depth blur, wind drift and realistic physics.",
    rows: ["particles", "canvas"],
    htmlPath: "/animations/snow-particles/index.html",
    cssPath: "/animations/snow-particles/styles.css",
    jsPath: "/animations/snow-particles/main.js",
  },
  {
    id: "27", slug: "confetti-burst",
    title: "Confetti Burst",
    category: "Canvas", categorySlug: "canvas", categoryIcon: "🌌",
    difficulty: "Intermediate",
    views: 37600, stars: 278, likes: 834,
    creator: "uicraft", creatorAvatar: "U", creatorColor: "#f59e0b",
    gradientFrom: "#f59e0b", gradientTo: "#ec4899",
    animationType: "particles",
    tags: ["confetti", "celebration", "canvas", "click"],
    description: "Physics-based confetti explosion triggered on click. Gravity, rotation and color variety.",
    isNew: true,
    rows: ["new", "particles"],
    htmlPath: "/animations/confetti-burst/index.html",
    cssPath: "/animations/confetti-burst/styles.css",
    jsPath: "/animations/confetti-burst/main.js",
  },
];

export const categories = [
  { id: "css",             name: "CSS Animations",     count: 142, icon: "✨", gradient: ["#8b5cf6", "#ec4899"], description: "Pure CSS magic with zero JS" },
  { id: "javascript",      name: "JavaScript Effects",  count: 98,  icon: "⚡", gradient: ["#f59e0b", "#ef4444"], description: "Dynamic interactive effects" },
  { id: "cursors",        name: "Cursor Effects",      count: 34,  icon: "🖱️", gradient: ["#06b6d4", "#3b82f6"], description: "Custom mouse interactions" },
  { id: "particles",      name: "Particle Systems",    count: 67,  icon: "🌌", gradient: ["#a855f7", "#3b82f6"], description: "Physics-based motion art" },
  { id: "loading",        name: "Loading Animations",  count: 89,  icon: "⏳", gradient: ["#3b82f6", "#8b5cf6"], description: "Elegant loaders & spinners" },
  { id: "text-effects",   name: "Text Effects",        count: 56,  icon: "📝", gradient: ["#10b981", "#06b6d4"], description: "Typography in motion" },
  { id: "threejs",        name: "Three.js",            count: 41,  icon: "🎲", gradient: ["#ec4899", "#f59e0b"], description: "3D browser experiences" },
  { id: "interactive-ui", name: "Interactive UI",      count: 73,  icon: "🎨", gradient: ["#ef4444", "#ec4899"], description: "UI microinteractions" },
];

export const creators = [
  {
    id: "1", name: "axeldev",    handle: "@axeldev",    avatar: "A",
    projects: 24, followers: 3200, color: "#8b5cf6", gradient: ["#8b5cf6", "#ec4899"],
    specialty: "CSS & GSAP", bio: "Frontend wizard crafting impossible CSS animations since 2018.",
    topProject: "Neon Orbit System",
  },
  {
    id: "2", name: "motioncraft", handle: "@motioncraft", avatar: "M",
    projects: 18, followers: 2800, color: "#06b6d4", gradient: ["#06b6d4", "#3b82f6"],
    specialty: "Canvas & WebGL", bio: "Canvas artisan. If it moves, I built it from scratch.",
    topProject: "3D Floating Cards",
  },
  {
    id: "3", name: "stardustfx",  handle: "@stardustfx",  avatar: "S",
    projects: 31, followers: 5100, color: "#ec4899", gradient: ["#ec4899", "#a855f7"],
    specialty: "Particle Systems", bio: "Galaxy-brained developer obsessed with particle physics.",
    topProject: "Particle Galaxy Field",
  },
  {
    id: "4", name: "chromawave",  handle: "@chromawave",  avatar: "C",
    projects: 15, followers: 1900, color: "#10b981", gradient: ["#10b981", "#06b6d4"],
    specialty: "CSS Gradients", bio: "Color theory meets code. Every gradient tells a story.",
    topProject: "Aurora Gradient Flow",
  },
];

/* ─── Netflix row definitions ─── */
export interface NetflixRowDef {
  id: string;
  labelKey: string;       // key into STRINGS[lang]
  categoryFilter?: string; // filter animations.rows includes this
  customFilter?: (a: AnimationProject) => boolean;
}

export const NETFLIX_ROWS: NetflixRowDef[] = [
  { id: "trending",  labelKey: "rowTrending",  customFilter: (a) => !!a.isTrending },
  { id: "new",       labelKey: "rowNew",        customFilter: (a) => !!a.isNew },
  { id: "css",       labelKey: "rowCSS",        categoryFilter: "css" },
  { id: "javascript",labelKey: "rowJS",          categoryFilter: "javascript" },
  { id: "particles", labelKey: "rowParticles",   categoryFilter: "particles" },
  { id: "canvas",    labelKey: "rowCanvas",      categoryFilter: "canvas" },
  { id: "threejs",   labelKey: "rowThreeJS",     categoryFilter: "threejs" },
  { id: "cursors",   labelKey: "rowCursors",     categoryFilter: "cursors" },
  { id: "loading",   labelKey: "rowLoading",     categoryFilter: "loading" },
  { id: "hearts",    labelKey: "rowHearts",      categoryFilter: "hearts" },
];
